language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
script:
- python run_testsuite.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: iX3F4sMmhq7Yt3qyVFGGE+FWy08tQhNodxCbytWSPENPT2BNj91pw50Zy5vMUHqM0Ypy/gR00w8PgwCqsH+r5vONr1fUA1+KMSgkSNB5PPY1I+9nO+DnUR1ZD1vEiDfwO8hpvqQ58bAbfgU1nLJ6Itd0z7p4gtBM+W/E60qqLuP1/trcNiBmQ72MZ9zMP0a/cgbEqiCqtQ6foeu9xWXpKaIRSznLYXLU8Q3hXMFrWe3DmBA/TUvFDjJbx+B1rvu1Vm1MSL4HltSj1AOQbtVYaeFGT1KViYzA8A8NWOfLPEV7SJsjUnLiLcrMddYIYNChzsvy6wcVKvIVD9PY21x4OYPSHiBN6YT/V+ECW8yb02qMZNMWRZBsjcSTQfFVc8QIcUnSx+GBIESDRvw4D4ST2x4ye1o2CdWOBwWrCbjcfvGykwJgvsiIAWojNyYhw+2jGynk6ioBWgWGgWv3cVZHCw2SR4NfrH8t6DiApWBn9mAEh4xHrmZVUXef4HrAMpCdSUiqP/hA+Ln2w2JCjiWAtmk50Q/zsQVGnpRmqIA54pydM07gFBAyGoEyIt29WqxZ85391looVsK3HyFIsPVQdWj6gRq2O1iYkBTxN9YhbZuir+v4Bf9hte/Vu/UvJyRbzX000v8p8FrBrHu6Uz0Gn16qVEAdvIsXM2ItcAuYwwo=
  on:
    tags: true
    all_branches: true
    python: 2.7
